name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write  # Enable OIDC token creation
      contents: read   # Read access to the repository

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::443370701748:role/testappadmin
          aws-region: us-east-1
      - name: Set up kubectl
        uses: aws-actions/eks-setup@v1
        with:
          cluster-name: app-project-eks-cluster-eksCluster-016cff5 # Replace with your EKS cluster name
          region: us-east-1


      # Step 8: Configure kubeconfig for cluster
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name app-project-eks-cluster-eksCluster-016cff5

      # Step 9: Deploy Helm chart
      - name: Deploy Helm Chart
        run: |
          kubectl get nodes
