name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write  # Enable OIDC token creation
      contents: read   # Read access to the repository

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::443370701748:role/testappadmin
          aws-region: us-east-1
      - name: Verify AWS Identity
        run: |
           aws sts get-caller-identity

      # Step 3: Update kubeconfig for EKS
      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name app-project-eks-cluster-eksCluster-016cff5

      # Step 4: Verify Kubernetes cluster connectivity
      - name: Verify Kubernetes Cluster
        run: |
          kubectl get nodes
